apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  namespace: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: phpmyadmin:latest
        env:
        - name: PMA_HOST
          valueFrom:
            secretKeyRef:
              name: wordpress-secret
              key: PMA_HOST
        - name: PMA_PORT
          value: "3306"
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64M"
            cpu: "10m"
          limits:
            memory: "200M"
            cpu: "150m"

---

apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  namespace: wordpress
spec:
  selector:
    app: phpmyadmin
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP